<?php

namespace Repository;

/**
 * DomyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomyRepository extends \Doctrine\ORM\EntityRepository
{
}
