<?php

namespace Repository;

/**
 * GruntyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GruntyRepository extends \Doctrine\ORM\EntityRepository
{
}
