<?php

namespace Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MieszkanieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MieszkanieRepository extends EntityRepository
{
    /**
     * @param array $szukaj
     * @return \Doctrine\ORM\Query
     */
    public function pobierzWszystko($szukaj = [])
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('m')
            ->from('Entity\Mieszkanie', 'm')
            ->join('m.nieruchomosc', 'n');

        if (!empty($szukaj['typ_oferty'])) {
            $qb->andWhere('n.typ_oferty = :typ_oferty');
            $qb->setParameter('typ_oferty', $szukaj['typ_oferty']);
        }
        if (!empty($szukaj['miasto'])) {
            $qb->andWhere('n.miasto = :miasto');
            $qb->setParameter('miasto', $szukaj['miasto']);
        }
        if (!empty($szukaj['powierzchnia-od'])) {
            $qb->andWhere('n.powierzchnia >= :powierzchnia');
            $qb->setParameter('powierzchnia', $szukaj['powierzchnia-od']);
        }

        if (!empty($szukaj['powierzchnia-do'])) {
            $qb->andWhere('n.powierzchnia <= :powierzchnia');
            $qb->setParameter('powierzchnia', $szukaj['powierzchnia-do']);
        }

        if (!empty($szukaj['cena-od'])) {
            $qb->andWhere('n.cena >= :cena');
            $qb->setParameter('cena', $szukaj['cena-od']);
        }

        if (!empty($szukaj['cena-do'])) {
            $qb->andWhere('n.cena <= :cena');
            $qb->setParameter('cena', $szukaj['cena-do']);
        }

        if (!empty($szukaj['rok_budowy'])) {
            $qb->andWhere('m.rok_budowy = :rok_budowy');
            $qb->setParameter('rok_budowy', $szukaj['rok_budowy']);
        }

        return $qb->getQuery();
    }
}
