<?php

namespace Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NieruchomoscRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NieruchomoscRepository extends EntityRepository
{
}
